branch-defaults:
  default:
    environment: Garymcmonagle-env
environment-defaults:
  Garymcmonagle-env:
    branch: null
    repository: null
global:
  application_name: garymcmonagle
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:eu-west-1::platform/Node.js running on
    64bit Amazon Linux/4.7.1
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-deploy-user
  sc: null
  workspace_type: Application
